[theme]
base = "light"
primaryColor = "#15803d"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f4f6"
textColor = "#1f2937"
font = "sans serif"

[server]
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false
